package main

import (
	"fmt"
	"github.com/gsora/hid-compiler/compiler"
)

var s1 = "this is a string"
var s2 = "this is a [LCTRL]>string too"
var s3 = "th[LSHIFT]:is is a string [LCTRL]>again"
var s4 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In in fringilla arcu. Vivamus sem nibh, elementum in sapien vel, iaculis sodales ligula. Ut ac rhoncus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis, risus pharetra imperdiet aliquam, est tellus cursus ante, eget imperdiet sem elit vel nisi. In dignissim, lacus non cursus semper, mauris sem tincidunt ex, nec cursus ipsum ipsum nec augue. Aliquam dignissim lectus vitae facilisis dictum. Proin varius sollicitudin est at mollis. Duis porttitor ultrices eros vel maximus. Sed cursus elit in lacus luctus suscipit. Mauris porttitor lectus sit amet felis hendrerit tempus. Etiam posuere posuere odio quis pulvinar. Vivamus euismod tempor pellentesque. Sed tincidunt libero dui, a bibendum ante hendrerit eget. Nulla varius lobortis pellentesque. Sed vitae ipsum congue, rutrum odio ut, porta metus.
Quisque risus urna, facilisis at ex vitae, sagittis lobortis neque. Morbi malesuada aliquam massa at tincidunt. Praesent nec molestie lacus, consectetur facilisis tortor. Pellentesque eget leo neque. Integer neque turpis, sodales non consectetur a, vestibulum a ligula. In sagittis et massa ut sagittis. Nulla id hendrerit ex. Curabitur lectus nunc, varius et pellentesque non, porta sed diam. Curabitur rutrum est nec nisl eleifend, nec ornare velit pretium. Integer eget justo urna. Sed massa massa, imperdiet vitae sodales vel, faucibus quis ante. Phasellus tincidunt justo a justo scelerisque aliquet. Aliquam fermentum metus consequat vulputate cursus. Fusce augue risus, scelerisque facilisis felis a, tristique pretium orci. Vivamus rutrum rutrum facilisis.
Donec consequat elementum risus nec tristique. Sed hendrerit urna quam, vel elementum quam tempor eu. Aliquam faucibus tincidunt dui, accumsan tempor orci aliquet et. Morbi id tristique nisl. Nulla facilisi. Curabitur id posuere lectus. Vivamus ac aliquam enim. Quisque molestie imperdiet ante in ullamcorper. Sed egestas ex aliquam metus sodales, luctus iaculis dui auctor. Quisque vitae euismod velit, et sollicitudin diam. Ut augue ante, viverra vitae suscipit ac, accumsan eget leo. Nunc consequat justo accumsan urna malesuada elementum. Etiam sit amet euismod tellus, a vehicula nulla. Vivamus at odio neque. Morbi consectetur convallis turpis, bibendum porttitor tellus accumsan a. Suspendisse porttitor magna in sodales viverra.
Vestibulum a augue magna. Nulla facilisi. Nullam congue diam a ex ultrices, quis facilisis ante congue. Vivamus placerat, neque ac malesuada sollicitudin, ipsum purus porttitor lectus, sit amet ullamcorper dui ex et odio. Ut ac mattis nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vitae odio aliquet, semper lorem vitae, pharetra urna. Ut ullamcorper purus id felis ullamcorper sagittis. Aenean sed urna luctus, sollicitudin ligula in, consequat felis. Aenean tortor orci, blandit quis nibh tincidunt, sollicitudin condimentum lectus. Integer iaculis purus sit amet pulvinar fringilla. Proin condimentum suscipit risus, at pulvinar leo aliquet sit amet. Donec eget nulla pharetra, sollicitudin orci at, semper tellus. Nullam consequat vestibulum nunc, sed finibus nulla.
Sed imperdiet blandit mi, quis luctus dolor aliquam sed. Donec maximus ipsum ac rhoncus volutpat. Mauris turpis nibh, mollis in posuere ut, scelerisque eu est. Maecenas dignissim dolor ultrices diam pellentesque luctus. Vivamus venenatis, eros ac vulputate venenatis, risus velit ultricies felis, nec dapibus diam leo vitae elit. Pellentesque quis arcu vitae ligula hendrerit tristique vitae ut ex. Sed tortor ex, feugiat vitae efficitur et, lobortis ut quam. Phasellus dapibus mauris vitae sagittis pretium. Fusce quis ligula lectus. Curabitur ornare ultrices vulputate. Duis sit amet lectus ac urna tincidunt convallis. Integer ut convallis lacus. Proin tortor nisl, hendrerit eu blandit ac, suscipit quis nunc. Nulla maximus maximus felis, vel gravida libero sodales at. Duis in nibh neque. Donec non euismod risus.
Sed ac ultricies nulla, cursus viverra leo. Sed mollis, nisi in vulputate dictum, purus nunc suscipit nibh, sit amet pharetra metus est id orci. Cras sit amet lobortis felis. Nunc consequat est lectus, nec vehicula purus ornare at. Duis eros lacus, ornare non magna non, imperdiet vehicula elit. Sed vitae euismod risus. Nulla facilisi. Phasellus tincidunt ac elit vehicula ornare. Nulla varius ipsum orci, sed dignissim quam viverra a. Fusce tincidunt, neque at dictum sollicitudin, orci ex efficitur eros, ac maximus ipsum est eu quam. Nunc porttitor ipsum eget dignissim blandit. Sed ac ante ac sapien convallis vulputate eu nec est. Maecenas nec ligula suscipit, molestie nisl sed, convallis sapien.
Vivamus rhoncus velit magna, ut mattis neque varius in. Maecenas rhoncus gravida velit, vitae porttitor mi egestas non. Mauris feugiat sagittis sem, ut ullamcorper felis dapibus id. Quisque accumsan, erat quis ultrices dignissim, odio diam condimentum arcu, feugiat malesuada urna velit nec sem. Quisque luctus lorem vitae eleifend blandit. Integer vitae sapien imperdiet, vehicula nulla at, auctor libero. Sed quis pharetra nibh, nec egestas orci. Vivamus mollis ornare tempor. Nam vitae ultrices nulla, vitae dignissim urna. Pellentesque lobortis ligula quis consectetur feugiat. Phasellus vel arcu non sem feugiat lobortis id sed eros.
Sed vel malesuada enim. Ut aliquam volutpat efficitur. Vivamus condimentum ipsum quis posuere viverra. Vestibulum tempor felis nisi, eu cursus enim aliquet a. Nam eu euismod lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis nibh urna, feugiat in aliquam lobortis, pellentesque eu enim. Aenean volutpat nunc ac tristique rutrum. Aenean malesuada tortor felis, non placerat nulla sodales ut. Vestibulum eget ipsum lectus. Fusce quis tortor et nisi gravida semper at eu libero. Suspendisse mi ipsum, cursus quis quam quis, ullamcorper bibendum nulla. Quisque laoreet sapien sed quam feugiat ullamcorper. Pellentesque nec velit nec sapien laoreet tempus vitae ac massa. Quisque iaculis ex metus, vel accumsan ipsum lacinia et.
In lacinia porta ultrices. Morbi aliquam aliquam erat sed tempus. Morbi consectetur ante sapien. Phasellus elementum mollis lacus eu molestie. Aenean sit amet ornare libero. Mauris ultricies ut dolor id varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean pulvinar tincidunt arcu eu luctus. Vestibulum nec velit sed velit auctor interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porta dolor interdum posuere lobortis. Curabitur at interdum eros. In interdum at dolor nec faucibus. Suspendisse eget odio nibh. Nam ut viverra magna.
Proin ac lacus augue. Quisque ut massa fringilla, luctus dolor sit amet, tempus risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla elit nulla, pretium quis pretium non, volutpat at nisi. Donec id est varius nunc dignissim ultricies id sit amet mi. Morbi varius augue vitae nibh maximus tristique. Fusce non gravida arcu.
Curabitur a aliquam lacus, sed ultrices tortor. Aenean sagittis sed lorem at tristique. Phasellus lacus lorem, malesuada ac lacinia non, dapibus at nulla. Vivamus purus sapien, luctus sit amet condimentum sit amet, auctor eget justo. In hac habitasse platea dictumst. Vivamus tempus sed dui a vestibulum. Nulla sollicitudin, lorem vitae lobortis mattis, ligula diam dictum massa, in fringilla purus erat et felis. In tincidunt tellus sed erat congue, a consequat erat sodales. Pellentesque euismod ipsum id diam pharetra, non congue magna dictum. Nullam varius porta augue vitae dictum. Donec vitae nisl ac elit tincidunt tincidunt. Sed luctus, nisl eget pellentesque lacinia, est ipsum volutpat nulla, vitae hendrerit nunc risus et justo.
Nam sem dui, scelerisque vitae ullamcorper vulputate, vestibulum sed lacus. Nam odio ante, bibendum a posuere sed, dictum varius est. Donec pulvinar, enim ut maximus fringilla, purus felis cursus ligula, vel efficitur nisl elit et sem. Vestibulum orci tortor, interdum a feugiat sed, auctor ac nulla. Vivamus sem ligula, tristique consequat neque vitae, blandit condimentum diam. Ut eu odio diam. Aenean pulvinar consectetur nisl. Fusce a lacus consectetur, vehicula enim non, tempor quam. Proin et lectus eros. Mauris id tincidunt justo.
Duis congue pellentesque ante sit amet venenatis. Ut malesuada ligula a urna sodales, tempor luctus odio aliquet. Maecenas ac lacus at lorem tincidunt lacinia. Aliquam erat volutpat. Sed at sapien ac neque facilisis accumsan vitae non velit. Vestibulum sagittis ligula eu hendrerit auctor. Sed ullamcorper, lacus ac ornare dignissim, ipsum erat convallis quam, vel mollis nisi augue et tellus. Nulla condimentum ornare lorem non mollis. Vestibulum libero ipsum, egestas lacinia rutrum a, dignissim vel arcu. Morbi eleifend erat nunc. Cras sit amet lobortis turpis.
Morbi consequat ultrices nisl, vel porta nulla dictum at. Proin pharetra ligula sit amet tempor cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In vel libero ultrices, pulvinar libero sed, tincidunt velit. Aenean porttitor rhoncus velit, id molestie lacus. Ut id dictum libero. Pellentesque gravida ultricies tellus at lobortis. Quisque non nibh ut ex dignissim viverra. Integer lacinia malesuada diam, vitae vehicula elit tincidunt a.
Aenean eleifend tincidunt nisi, a scelerisque arcu. Phasellus nisl lacus, pharetra sed placerat sed, viverra nec enim. Vestibulum leo nisi, porta ac ante sit amet, molestie consectetur dolor. Fusce suscipit porttitor est, ut auctor mauris vulputate at. Sed tempor, nunc ac accumsan varius, felis erat aliquam nisi, id aliquam mi nunc vitae dolor. Proin malesuada enim eu sem aliquam, non efficitur justo efficitur. Nulla rhoncus eros eros, nec tempor odio laoreet nec. Donec sit amet turpis rutrum, porta ipsum quis, posuere nibh.
Vestibulum viverra condimentum felis eget aliquet. Sed faucibus faucibus nulla, sit amet mollis metus tincidunt vel. Nulla facilisis dignissim felis, et mollis est rutrum vel. Cras sit amet nunc in enim feugiat convallis nec nec ipsum. Aenean dui eros, elementum ut laoreet ac, pulvinar at felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus a consectetur libero. Vivamus suscipit erat non massa suscipit, faucibus posuere tortor sagittis.
Etiam et ultricies tortor, et varius ligula. Quisque finibus ipsum vitae lacus convallis blandit. Pellentesque id leo sodales, venenatis ante sed, sagittis lorem. Vivamus vel nunc in est ornare auctor at et nulla. Donec vulputate porttitor neque eu maximus. Vivamus varius scelerisque erat, id egestas ipsum fermentum eu. Nulla sed orci vestibulum, vestibulum massa non, interdum mauris. Fusce mollis blandit felis quis placerat. Ut sit amet vehicula urna, in hendrerit arcu. Aliquam mattis eros non pretium convallis. Aliquam erat volutpat.
Curabitur lacus nunc, cursus et ultricies sed, lacinia in tortor. Morbi interdum eleifend diam, in scelerisque mi tempus tempus. Pellentesque felis tortor, fringilla sit amet rutrum eget, euismod nec diam. Nulla sit amet diam non ligula accumsan posuere quis sagittis orci. Mauris porttitor orci et suscipit pulvinar. Curabitur facilisis, quam at viverra ultrices, est mi cursus ligula, in efficitur sapien mi id felis. In a bibendum ex, nec varius purus. Vivamus eget fringilla ipsum, eu cursus elit. Donec eget massa a felis lobortis consequat in ac dolor. Nulla convallis malesuada aliquet. Proin porttitor mauris eget tincidunt semper. Ut posuere vehicula dolor, in ultrices tortor placerat ac. Proin viverra tortor at dui suscipit ultricies ut et sem.
Duis vitae neque sapien. Proin mattis justo quis nunc tincidunt egestas. Donec sodales lacus quis urna pulvinar, id luctus magna feugiat. Cras molestie purus fermentum, commodo libero et, semper ex. Curabitur maximus nunc in massa dapibus molestie. Nunc consequat, erat sed scelerisque egestas, lectus mi congue augue, quis eleifend felis justo nec leo. Donec sit amet vulputate elit, eget mattis leo. Donec a ante a velit facilisis rhoncus id sed dolor. Aenean felis elit, ultrices a ligula a, placerat tempor massa. Proin eu felis eu libero maximus sagittis sed vel velit.
Donec neque nisl, gravida sit amet nibh at, ultrices lacinia magna. Nullam mollis lectus id felis porttitor, a pellentesque quam vestibulum. Donec accumsan elit ante, vel consequat lacus tempor ac. Quisque rhoncus in nulla nec tincidunt. Fusce accumsan urna ac interdum mollis. Phasellus sed tristique risus, vitae ultricies mi. Aliquam congue dolor id enim ultricies, scelerisque maximus quam feugiat. Suspendisse aliquet nibh nibh, nec pretium nulla gravida ac. Aliquam convallis sollicitudin magna, a ultrices libero interdum vel.
In pellentesque nisl in tortor hendrerit, at pellentesque neque dignissim. Integer nisi augue, viverra nec erat in, laoreet maximus tortor. Cras congue et orci sit amet tincidunt. Proin eu est at massa sagittis auctor. Donec consequat lobortis nunc id fermentum. Sed molestie mi vitae ultrices blandit. Aenean id arcu egestas, viverra quam luctus, volutpat tortor. Vivamus laoreet dictum elit, at placerat purus auctor vitae. Donec convallis sed nisi ut ornare. Praesent eleifend, arcu sit amet ultrices interdum, mi est euismod mauris, in mollis ligula eros et sem. Quisque nisi orci, posuere sed vulputate placerat, aliquet et mi. In hac habitasse platea dictumst. Pellentesque ac commodo lorem, ut tempus justo.
Sed est nulla, dignissim ut turpis eget, cursus imperdiet leo. In vel viverra nisl. Mauris vitae lacus congue, faucibus orci vitae, rhoncus lacus. Quisque rhoncus posuere nisl, nec iaculis ex. Aenean rhoncus nibh augue. Suspendisse at felis vitae tortor ullamcorper accumsan. Vivamus hendrerit eu enim ut luctus. Etiam faucibus orci nec leo placerat lobortis. Sed mattis justo non turpis molestie, non sagittis lorem molestie. Proin eu sodales neque, sit amet iaculis sapien. Curabitur porttitor ante sit amet nibh tincidunt, sed vestibulum magna fermentum. Nam vulputate sodales ante non fermentum. Aliquam sit amet mollis leo. Nullam ligula nunc, efficitur quis tempor quis, aliquam non sem. Maecenas fermentum finibus diam, at lacinia neque.
Nullam arcu felis, pulvinar nec pharetra eu, dignissim a ex. Sed libero est, scelerisque sed nibh a, pellentesque euismod diam. Vestibulum ultrices a purus ac porttitor. Cras pharetra mattis diam id maximus. In dolor metus, viverra non nisi auctor, efficitur faucibus nisi. Nam cursus, nisl bibendum egestas eleifend, tellus lorem rhoncus quam, sed bibendum sem dui ut est. Pellentesque sit amet dolor et mi sodales dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vulputate, nunc ac vehicula lacinia, massa arcu facilisis justo, eu congue felis tellus ut massa. Suspendisse faucibus mattis ligula sed volutpat. Fusce eget arcu enim. Praesent feugiat iaculis lorem, at dictum dui eleifend sed. Vivamus varius mauris ac eleifend sollicitudin. Nulla facilisi.
Suspendisse iaculis risus magna, non vehicula risus cursus vel. In enim sapien, molestie id lorem eget, aliquet rhoncus risus. Maecenas lobortis dolor in enim ultricies, a porttitor justo tincidunt. Suspendisse accumsan rhoncus nunc, vel ultricies dui. In ac massa et nibh sagittis efficitur. Nullam est orci, sodales et euismod ac, vulputate sed libero. Suspendisse sit amet nunc consequat, commodo nisi vitae, bibendum lacus. Proin bibendum nec mi nec malesuada. Cras blandit nibh eu orci aliquam, eget bibendum lacus iaculis. Fusce vitae erat non ex dapibus hendrerit.
Quisque tristique mi et cursus scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vitae dictum nibh. Morbi vel interdum urna. Nam iaculis, lorem ac tristique hendrerit, dolor risus hendrerit tortor, eu sodales nisl massa eget dolor. Donec facilisis lobortis eros, in mattis leo. Maecenas tempor dapibus porttitor. Suspendisse ornare tellus nec dapibus commodo. Duis ultricies justo nisl, nec pulvinar nisi luctus et. Fusce orci lacus, convallis eget lobortis id, placerat quis magna. Morbi pretium dolor vehicula libero sodales convallis. Suspendisse convallis commodo metus vitae condimentum. Praesent rhoncus augue eget libero efficitur tincidunt. Nunc eleifend feugiat felis, eu varius nibh vehicula placerat. Phasellus ullamcorper felis malesuada libero rhoncus pharetra. Donec ornare aliquet turpis, sed pretium magna iaculis ut.
Mauris nec nunc nisl. Nulla facilisi. Etiam lacinia orci in tempus dapibus. Pellentesque est justo, feugiat nec urna quis, consequat imperdiet est. Nulla vel tortor aliquet, semper augue et, ultricies leo. Etiam ac eros a ex pretium tristique vestibulum in metus. Duis vel blandit quam. Praesent id vulputate ex. Vivamus et fringilla diam. Nulla facilisi. Praesent gravida massa quis ligula dictum lobortis. Donec commodo accumsan massa, sed porta libero euismod fermentum. Maecenas justo lorem, bibendum at lectus sit amet, scelerisque pharetra est.
Vivamus varius maximus magna a pretium. Curabitur augue mauris, fermentum sit amet massa vel, interdum dignissim purus. Fusce lacinia tincidunt tempor. Donec volutpat consectetur felis. Mauris quam felis, ultricies vitae massa sit amet, mollis maximus metus. Phasellus mollis viverra bibendum. Nunc semper ipsum eu fringilla fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tincidunt efficitur gravida. Donec id commodo quam. Nunc at tempus mi. Nam venenatis justo sit amet lacus porttitor fermentum.
Vestibulum porta vulputate molestie. Phasellus laoreet justo at faucibus convallis. Duis neque neque, bibendum sed dictum eget, eleifend at elit. Duis nisl ipsum, suscipit et tristique sit amet, mollis vestibulum dui. Nunc a dictum lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt efficitur dignissim. Nullam tellus justo, laoreet eu placerat id, tincidunt sit amet tellus. Mauris nec nulla eget erat mattis gravida. Sed posuere ligula eget arcu maximus, quis tincidunt dui venenatis. Vivamus congue efficitur lorem pretium faucibus. Vestibulum tellus sapien, egestas quis tincidunt vitae, suscipit at odio. Etiam vel rhoncus purus. Cras non augue venenatis, vehicula magna at, eleifend justo. Sed aliquam, eros vel gravida aliquam, dolor tortor sagittis metus, accumsan tincidunt lorem neque non urna. Nunc blandit porttitor commodo.
Fusce vel elit ligula. Mauris maximus magna nunc, nec bibendum nisi consectetur sed. Donec at ultrices quam. Nulla lacinia dapibus metus vitae placerat. Quisque vitae laoreet tellus, et consectetur orci. Vestibulum diam quam, tincidunt at aliquam in, porttitor accumsan metus. Phasellus condimentum eget lacus at placerat. Pellentesque urna metus, consectetur in dapibus et, tristique non ante. Donec ut vestibulum nisi. Sed sed lorem lobortis, maximus lacus a, semper dui. Mauris bibendum condimentum iaculis.
Suspendisse a felis purus. Nulla id ultrices odio. Curabitur tempus in dui quis tristique. Vivamus tellus odio, consectetur sed ultrices consectetur, tristique fermentum nunc. Curabitur neque ex, tristique id semper ac, blandit quis magna. Ut convallis mollis nisl, vitae convallis diam dictum vitae. Duis ac sem arcu. Ut et accumsan augue, at lobortis magna. Curabitur commodo arcu sit amet blandit pulvinar.
Aenean tortor odio, vulputate ac porta vitae, semper in velit. Quisque vestibulum, tortor at aliquam feugiat, est ex consequat est, eu gravida dolor justo id felis. Nullam dignissim sed dui at iaculis. Pellentesque eu leo vel tortor consectetur condimentum at nec urna. Donec in erat et nunc convallis elementum et non neque. Nunc porta dui vitae felis tristique fermentum. Morbi sed condimentum lacus. Duis et quam tellus. Phasellus fermentum, eros eget commodo eleifend, nibh nibh fermentum justo, sit amet mattis quam ante bibendum quam. In eu sapien id tellus pulvinar malesuada ut vitae velit. Curabitur in ex sed ipsum ultricies blandit. Aliquam in dapibus lectus. Morbi eget posuere risus, ac vestibulum dui. Praesent dignissim pellentesque venenatis. Quisque at orci eget nibh gravida iaculis at at dui. Donec sagittis nibh et nisi suscipit, venenatis luctus lectus eleifend.
Pellentesque faucibus arcu quis blandit lacinia. Fusce id sodales tortor, id efficitur magna. Maecenas leo ex, facilisis eu semper molestie, venenatis sed ex. Curabitur venenatis vehicula lacus non condimentum. Aliquam vel magna tortor. Fusce facilisis vulputate libero, volutpat laoreet urna vestibulum ut. Integer eu elementum leo. Aenean ornare purus mauris, finibus faucibus lectus aliquam vel. Quisque feugiat interdum massa, in efficitur diam semper interdum. Etiam placerat aliquet tristique. Vestibulum sem ex, consectetur at sollicitudin id, lobortis in tellus. Duis ac euismod ipsum, non aliquet sapien.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse ut semper nunc. Donec sagittis sit amet risus sit amet tincidunt. Cras porta congue lacus, sit amet posuere massa mattis non. Suspendisse sit amet egestas quam. Donec lacinia fermentum ipsum vitae porttitor. Vivamus tristique diam ac est consequat pharetra. Proin sodales, orci id consequat efficitur, neque dui faucibus massa, a tincidunt erat sapien ac purus. Duis hendrerit nunc augue, at volutpat odio pellentesque quis. Etiam ultricies dignissim ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed euismod molestie ultrices. Proin eget pulvinar massa, at ullamcorper ex. Mauris dapibus nibh eu turpis pulvinar, nec elementum libero ultrices.
Sed tincidunt vel eros vestibulum viverra. Praesent bibendum sapien at mauris gravida ornare. Fusce eu nisi ultricies, ullamcorper nibh nec, malesuada mauris. Cras ut rhoncus nisl, eget rhoncus est. Duis ut faucibus enim. Praesent facilisis sed justo ut tincidunt. Proin eu nisi sed orci ultrices iaculis.
Proin nec augue a arcu sagittis sollicitudin. Suspendisse scelerisque rhoncus pretium. Nunc eu diam nisl. In tincidunt dictum dui eget elementum. In vitae interdum odio, vitae mattis mauris. Cras commodo dictum commodo. Aenean lacinia ultrices mi. Nullam dignissim, velit in condimentum elementum, massa justo feugiat justo, in dignissim arcu turpis id augue. Donec sodales, enim vel malesuada consectetur, metus magna vehicula est, sit amet congue turpis libero eget leo.`

func main() {

	l := compiler.Compile(s4)
	fmt.Println(l)
}
