// Code generated by "stringer -type=Modifier"; DO NOT EDIT.

package modifiers

import "fmt"

const (
	_Modifier_name_0 = "LCTRLLSHIFT"
	_Modifier_name_1 = "LALT"
	_Modifier_name_2 = "LMETA"
	_Modifier_name_3 = "RCTRL"
	_Modifier_name_4 = "RSHIFT"
	_Modifier_name_5 = "RALT"
	_Modifier_name_6 = "RMETA"
	_Modifier_name_7 = "NOMOD"
)

var (
	_Modifier_index_0 = [...]uint8{0, 5, 11}
	_Modifier_index_1 = [...]uint8{0, 4}
	_Modifier_index_2 = [...]uint8{0, 5}
	_Modifier_index_3 = [...]uint8{0, 5}
	_Modifier_index_4 = [...]uint8{0, 6}
	_Modifier_index_5 = [...]uint8{0, 4}
	_Modifier_index_6 = [...]uint8{0, 5}
	_Modifier_index_7 = [...]uint8{0, 5}
)

func (i Modifier) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Modifier_name_0[_Modifier_index_0[i]:_Modifier_index_0[i+1]]
	case i == 4:
		return _Modifier_name_1
	case i == 8:
		return _Modifier_name_2
	case i == 16:
		return _Modifier_name_3
	case i == 32:
		return _Modifier_name_4
	case i == 64:
		return _Modifier_name_5
	case i == 128:
		return _Modifier_name_6
	case i == 256:
		return _Modifier_name_7
	default:
		return fmt.Sprintf("Modifier(%d)", i)
	}
}
